{
 "title": "Themelio-Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values({network=~\"$network\"}, hostname) "
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({network=~\"$network\", hostname=~\"$hostname\"}, instance) "
    }
   },
   { "name": "timeframe", "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Highest Block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(themelio_node_highest_block{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Uptime (Themelio-Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(themelio_node_uptime_seconds{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Uptime (System)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(themelio_node_system_uptime_seconds{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_network_transmitted_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_network_received_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_memory_total_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_memory_free_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Root Filesystem Total Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_root_filesystem_total_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "Root Filesystem Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_root_filesystem_free_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (User, Timeframe Adjustable)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(themelio_node_cpu_load_user_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}[$__interval])) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (System, Timeframe Adjustable)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(themelio_node_cpu_load_system_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}[$__interval])) by (network, hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (Idle, Timeframe Adjustable)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(themelio_node_cpu_load_idle_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}[$__interval])) by (network, hostname, instance)"
    }
   ]
  }
 ]
}