log_level = "DEBUG"

[proxy]
listening_hostname = "loki.themelio.org"
forwarding_hostname = "loki"
forwarding_port = 3100
admin_email = "meade@themelio.org"

[http]
port = 80

[https]
enabled = true
port = 443