{
 "title": "Themelio-Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values({network=~\"$network\"}, hostname) "
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({network=~\"$network\", hostname=~\"$hostname\"}, instance) "
    }
   },
   {
    "name": "ip_address",
    "query": {
     "query": "label_values({network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\",}, ip_address) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Logs (By IP Address)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"public_ip=$ip_address\""
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(themelio_node_uptime_seconds{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Highest Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(themelio_node_highest_block{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_network_received_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_network_transmitted_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_memory_free_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_memory_total_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Root Filesystem Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_root_filesystem_free_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "Root Filesystem Total Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(themelio_node_root_filesystem_total_bytes{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (User)",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(themelio_node_cpu_load_user_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (System)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(themelio_node_cpu_load_system_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  },
  {
   "title": "CPU Load (Idle)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(themelio_node_cpu_load_idle_percentage{network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\"}) by (hostname, instance)"
    }
   ]
  }
 ]
}