global:
  scrape_interval:     {{ cfg.scrape_interval }}
  evaluation_interval: {{ cfg.evaluation_interval }}

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']