global:
  scrape_interval:     {{ cfg.scrape_interval }}
  evaluation_interval: {{ cfg.evaluation_interval }}

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'openstack-bhs5'
    openstack_sd_configs:
      - role: 'instance'
        region: 'BHS5'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-de1'
    openstack_sd_configs:
      - role: 'instance'
        region: 'DE1'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-gra5'
    openstack_sd_configs:
      - role: 'instance'
        region: 'GRA5'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-gra7'
    openstack_sd_configs:
      - role: 'instance'
        region: 'GRA7'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-gra9'
    openstack_sd_configs:
      - role: 'instance'
        region: 'GRA9'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-gra11'
    openstack_sd_configs:
      - role: 'instance'
        region: 'GRA11'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-sbg5'
    openstack_sd_configs:
      - role: 'instance'
        region: 'SBG5'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-sgp1'
    openstack_sd_configs:
      - role: 'instance'
        region: 'SGP1'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-syd1'
    openstack_sd_configs:
      - role: 'instance'
        region: 'SYD1'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-uk1'
    openstack_sd_configs:
      - role: 'instance'
        region: 'UK1'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'

  - job_name: 'openstack-waw1'
    openstack_sd_configs:
      - role: 'instance'
        region: 'WAW1'
        identity_endpoint: 'https://auth.cloud.ovh.net/v3'
        domain_name: 'default'
        username: '$OS_USERNAME'
        password: '$OS_PASSWORD'
    relabel_configs:
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: __address__
        action: replace
        replacement: '${1}:8080'
      - source_labels: [ __meta_openstack_private_ip ]
        target_label: ip_address
        replacement: '${1}'