name: "Prerequisites"
description: "Set up everything for biome."
inputs:
  BIOME_PUBLIC_KEY:
    description: 'The biome public key, fetched from secrets.'
    required: true
  BIOME_SIGNING_KEY:
    description: 'The biome signing key, fetched from secrets.'
    required: true
runs:
  using: "composite"
  steps:
    - run: sudo apt update
      shell: bash

    - run: curl -L "https://github.com/biome-sh/biome/releases/download/v$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv
      env:
        BIOME_VERSION: "1.6.372"
      shell: bash

    - run: sudo mv bio /usr/local/bin/bio
      shell: bash

    - run: sudo apt remove -y curl
      shell: bash

    - run: echo "$BIOME_PUBLIC_KEY" | bio origin key import
      env:
        BIOME_PUBLIC_KEY: ${{ inputs.BIOME_PUBLIC_KEY }}
      shell: bash

    - run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import
      env:
        BIOME_PUBLIC_KEY: ${{ inputs.BIOME_PUBLIC_KEY }}
      shell: bash

    - run: echo "$BIOME_SIGNING_KEY" | bio origin key import
      env:
        BIOME_SIGNING_KEY: ${{ inputs.BIOME_SIGNING_KEY }}
      shell: bash

    - run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import
      env:
        BIOME_SIGNING_KEY: ${{ inputs.BIOME_SIGNING_KEY }}
      shell: bash




#name: "Prerequisites"
#description: "Set up everything for biome."
#runs:
#  using: "composite"
#  steps:
#    - name: Update Apt
#      run: sudo apt update
#
#      - run: curl -L "https://github.com/biome-sh/biome/releases/download/v$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv
#        env:
#          BIOME_VERSION: "1.6.372"
#        shell: bash
#
#    - name: Install Biome
#      run: sudo mv bio /usr/local/bin/bio
#      shell: bash
#
#    - name: Remove Curl To Prevent Biome Conflicts
#      run: sudo apt remove -y curl
#      shell: bash
#
#    - name: Import Public Key
#      env:
#        BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#      run: echo "$BIOME_PUBLIC_KEY" | bio origin key import
#      shell: bash
#
#    - name: Import Public Key (sudo)
#      env:
#        BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#      run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import
#      shell: bash
#
#    - name: Import Signing Key
#      env:
#        BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#      run: echo "$BIOME_SIGNING_KEY" | bio origin key import
#      shell: bash
#
#    - name: Import Signing Key (sudo)
#      env:
#        BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#      run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import
#      shell: bash