{
 "title": "Themelio-Node Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "hostname",
    "query": {
     "query": "label_values({network=~\"$network\"}, hostname) "
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({network=~\"$network\", hostname=~\"$hostname\"}, instance) "
    }
   },
   {
    "name": "ip_address",
    "query": {
     "query": "label_values({network=~\"$network\", hostname=~\"$hostname\", instance=~\"$instance\",}, ip_address) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"ERROR\" | logfmt | public_ip = ip(`$ip_address`)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"WARN\" | logfmt | public_ip = ip(`$ip_address`)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"DEBUG\" | logfmt | public_ip = ip(`$ip_address`)"
    }
   ]
  }
 ]
}