server:
  http_listen_address: 0.0.0.0
  http_listen_port: {{cfg.http_port}}
  grpc_listen_address: ""
  grpc_listen_port: {{cfg.grpc_port}}

positions:
  filename: {{pkg.svc_var_path}}/positions.yaml

clients:
  - url: {{cfg.loki_url}}
  {{ ~#if cfg.basic_auth_enabled }}
  - basic_auth:
      username: $BASIC_AUTH_USER
      password: $BASIC_AUTH_PASSWORD
  {{/if}}

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - output:
          source: output