server:
  http_listen_address: 0.0.0.0
  http_listen_port: {{cfg.port}}

positions:
  filename: {{pkg.svc_var_path}}/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: {{pkg.svc_var_path}}/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'