name: "Prerequisites"
description: "Set up everything for biome."
runs:
  using: "composite"
  steps:
    - name: Update Apt
      run: sudo apt update

    - name: Download Biome
      env:
        BIOME_VERSION: "1.6.372"
      run: curl -L "https://github.com/biome-sh/biome/releases/download/v$BIOME_VERSION/bio-$BIOME_VERSION-x86_64-linux.tar.gz" | tar zxv

    - name: Install Biome
      run: sudo mv bio /usr/local/bin/bio

    - name: Remove Curl To Prevent Biome Conflicts
      run: sudo apt remove -y curl

    - name: Import Public Key
      env:
        BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
      run: echo "$BIOME_PUBLIC_KEY" | bio origin key import

    - name: Import Public Key (sudo)
      env:
        BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
      run: echo "$BIOME_PUBLIC_KEY" | sudo bio origin key import

    - name: Import Signing Key
      env:
        BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
      run: echo "$BIOME_SIGNING_KEY" | bio origin key import

    - name: Import Signing Key (sudo)
      env:
        BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
      run: echo "$BIOME_SIGNING_KEY" | sudo bio origin key import