name: BuildAndPublish

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Caddy Plans

  build-caddy-grafana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('caddy-grafana/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./caddy-grafana/scripts/ci-publish.sh


  build-caddy-prometheus:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('caddy-prometheus/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./caddy-prometheus/scripts/ci-publish.sh


  build-caddy-loki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('caddy-loki/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./caddy-loki/scripts/ci-publish.sh


# Go Plans

  build-go17:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go17/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./go17/scripts/ci-publish.sh


  build-go-if-go17-changed:
    needs:
      - build-go17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./go/scripts/ci-publish.sh


# Services

  build-grafana-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('grafana/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./grafana/scripts/ci-publish.sh

  build-loki-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('loki/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./loki/scripts/ci-publish.sh

  build-prometheus-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('prometheus/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./prometheus/scripts/ci-publish.sh

  build-promtail-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Apt
        run: sudo apt update

      - name: Install TzData
        run: env DEBIAN_FRONTEND="noninteractive" sudo apt install -y tzdata

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('prometheus/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build, Publish Artifact And Mark As Stable, Export And Publish Docker Image
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          HAB_BLDR_URL: "https://bldr.habitat.sh"
          BIOME_BLDR_URL: "https://bldr.biome.sh"
          BIOME_AUTH_TOKEN: ${{ secrets.BIOME_AUTH_TOKEN }}
          HABITAT_AUTH_TOKEN: ${{ secrets.HABITAT_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        run: ./prometheus/scripts/ci-publish.sh