name: BuildAndTest

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

# Verify Section

  testy-thing:
    runs-on: ubuntu-latest

    steps:

    - uses: themeliolabs/actions-biome@v1
      with:
        BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
        BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

    - name: Uninstall
      run: sudo apt -y remove net-tools

    - name: Install
      run: sudo bio pkg install --binlink core/net-tools --force

  verify-go17:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- go17 || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-go:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- go || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-grafana:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- grafana || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-loki:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- loki || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-prometheus:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- prometheus || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-promtail:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- promtail || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"


# Build Go17 And Go Section

  build-go17:
    needs: verify-go17
    if: contains(needs.verify-go17.outputs.build, 'true')
    runs-on: ubuntu-latest

    outputs:
      complete: ${{ steps.build.outputs.complete }}

    steps:
      - uses: actions/checkout@v2

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: ~/.hab/cache
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go17/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test Build Go17
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bio pkg build go17

      - name: Copy Hart File
        run: cp $(ls -1t results/themelio-go17-*.hart | head -1) results/go17-dev.hart

      - name: Create Hart Export
        uses: actions/upload-artifact@v2
        with:
          name: go17-dev
          path: results/go17-dev.hart

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "COMPLETE=true" >> $GITHUB_ENV

      - name: Echo COMPLETE Environment Variable
        run: echo ${{ env.COMPLETE }}

      - name: Check For Changes
        id: build
        if: ${{ env.COMPLETE == 'true' }}
        run: echo "::set-output name=complete::true"

  build-go:
    needs:
      - verify-go17
      - verify-go
    if: contains(needs.verify-go.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true')
    runs-on: ubuntu-latest

    outputs:
      complete: ${{ steps.build.outputs.complete }}

    steps:
      - name: Thingy
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "COMPLETE=true" >> $GITHUB_ENV

      - name: Echo COMPLETE Environment Variable
        run: echo ${{ env.COMPLETE }}

      - name: Check For Changes
        id: build
        if: ${{ env.COMPLETE == 'true' }}
        run: echo "::set-output name=complete::true"

  build-go-if-go17-changed:
    needs:
      - verify-go17
      - verify-go
      - build-go17
    if: contains(needs.verify-go.outputs.build, 'true') && contains(needs.verify-go17.outputs.build, 'true') && contains(needs.build-go17.outputs.complete, 'true')
    runs-on: ubuntu-latest

    outputs:
      complete: ${{ steps.build.outputs.complete }}

    steps:
      - uses: actions/checkout@v2

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: ~/.hab/cache
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Test Build Go
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bio pkg build go

      - name: Copy Hart File
        run: cp $(ls -1t results/themelio-go-*.hart | head -1) results/go-go17-changed-dev.hart

      - name: Create Hart Export
        uses: actions/upload-artifact@v2
        with:
          name: go-go17-changed-dev
          path: results/go-go17-changed-dev.hart

#  go-go17-changed-dev

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "COMPLETE=true" >> $GITHUB_ENV

      - name: Echo COMPLETE Environment Variable
        run: echo ${{ env.COMPLETE }}

      - name: Check For Changes
        id: build
        if: ${{ env.COMPLETE == 'true' }}
        run: echo "::set-output name=complete::true"



# Go17 And Go Change Plan Builds

  build-grafana-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
      - verify-grafana
    if: contains(needs.build-go17.outputs.complete, 'true') && contains(needs.build-go-if-go17-changed.outputs.complete, 'true') && contains(needs.verify-grafana.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: go17-dev

      - uses: actions/download-artifact@v2
        with:
          name: go-go17-changed-dev

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Install Go17
        run: sudo bio pkg install go17-dev.hart

      - name: Install Go
        run: sudo bio pkg install go-go17-changed-dev.hart

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('grafana/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./grafana/scripts/ci-test.sh

  build-loki-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
      - verify-loki
    if: contains(needs.build-go17.outputs.complete, 'true') && contains(needs.build-go-if-go17-changed.outputs.complete, 'true') && contains(needs.verify-loki.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: go17-dev

      - uses: actions/download-artifact@v2
        with:
          name: go-go17-changed-dev

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Install Go17
        run: sudo bio pkg install go17-dev.hart

      - name: Install Go
        run: sudo bio pkg install go-go17-changed-dev.hart

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Remove net-tools
        run: sudo apt -y remove net-tools

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('loki/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./loki/scripts/ci-test.sh

  build-prometheus-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
      - verify-prometheus
    if: contains(needs.build-go17.outputs.complete, 'true') && contains(needs.build-go-if-go17-changed.outputs.complete, 'true') && contains(needs.verify-prometheus.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: go17-dev

      - uses: actions/download-artifact@v2
        with:
          name: go-go17-changed-dev

      - uses: themeliolabs/actions-biome@v1
        with:
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}

      - name: Install Go17
        run: sudo bio pkg install go17-dev.hart

      - name: Install Go
        run: sudo bio pkg install go-go17-changed-dev.hart

      - name: Fix Directory Permissions
        run: sudo chown -R $(whoami):$(id -ng) /hab

      - name: Cache Biome
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-biome
        with:
          path: |
            ~/.hab/cache/artifacts
            /hab/cache/artifacts
            /hab/pkgs
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('prometheus/plan.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build, Run BATS Tests
        env:
          HAB_ORIGIN: "themelio"
          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./prometheus/scripts/ci-test.sh

  build-promtail-if-go17-and-go-changed:
    needs:
      - build-go17
      - build-go-if-go17-changed
      - verify-promtail
    if: contains(needs.build-go17.outputs.complete, 'true') && contains(needs.build-go-if-go17-changed.outputs.complete, 'true') && contains(needs.verify-promtail.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}


# Go Change Builds

  build-grafana-if-go-changed:
    needs:
      - verify-go17
      - verify-grafana
      - build-go
    if: contains(needs.verify-go.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && contains(needs.verify-grafana.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-loki-if-go-changed:
    needs:
      - verify-go17
      - verify-loki
      - build-go
    if: contains(needs.verify-go.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && contains(needs.verify-loki.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-prometheus-if-go-changed:
    needs:
      - verify-go17
      - verify-prometheus
      - build-go
    if: contains(needs.verify-go.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && contains(needs.verify-prometheus.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-promtail-if-go-changed:
    needs:
      - verify-go17
      - verify-promtail
      - build-go
    if: contains(needs.verify-go.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && contains(needs.verify-promtail.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

# Plan-Only Change Builds

  build-grafana:
    needs:
      - verify-go17
      - verify-go
      - verify-grafana
    if: contains(needs.verify-grafana.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && !contains(needs.verify-go.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-loki:
    needs:
      - verify-go17
      - verify-go
      - verify-loki
    if: contains(needs.verify-loki.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && !contains(needs.verify-go.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-prometheus:
    needs:
      - verify-go17
      - verify-go
      - verify-prometheus
    if: contains(needs.verify-prometheus.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && !contains(needs.verify-go.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}

  build-promtail:
    needs:
      - verify-go17
      - verify-go
      - verify-promtail
    if: contains(needs.verify-promtail.outputs.build, 'true') && !contains(needs.verify-go17.outputs.build, 'true') && !contains(needs.verify-go.outputs.build, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}







#  build-grafana-if-go17-changed:
#    needs:
#      - verify-go17
#      - verify-go
#      - verify-grafana
#      - build-go17
#    if: contains(needs.verify-go.outputs.build, 'true') && contains(needs.verify-go17.outputs.build, 'true') && contains(needs.build-go17.outputs.complete, 'true')
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Show Go17 Verify Output
#        run: echo ${{ needs.verify-go17.outputs.build }}
#
#      - name: Show Go17 Build Output
#        run: echo ${{ needs.build-go17.outputs.complete }}








#  build:
#    if: ${{ env.CHANGED == 'true' }}
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: themeliolabs/actions-biome@v1
#        with:
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#
#      - name: Cache Biome
#        uses: actions/cache@v2
#        env:
#          CACHE_NAME: cache-biome
#        with:
#          path: ~/.hab/cache
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go17/plan.sh') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - name: Test
#        env:
#          HAB_ORIGIN: "themelio"
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: bio pkg build go17
#
#
##      - name: Build, Run BATS Tests
##        env:
##          HAB_ORIGIN: "themelio"
##          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##        run: ./biome/themelio-node/scripts/ci-test.sh