name: TestAndBuildGo

on:
#  pull_request:
#    paths:
#      - 'go/**'
#    branches: [ master ]
  workflow_run:
    workflows:
      - TestAndBuildGo17
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: themeliolabs/actions-biome@v1
#        with:
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#
#      - name: Cache Biome
#        uses: actions/cache@v2
#        env:
#          CACHE_NAME: cache-biome
#        with:
#          path: ~/.hab/cache
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go/plan.sh') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - name: List
#        run: ls -la ~/.hab/cache/artifacts
#
#      - name: Test
#        env:
#          HAB_ORIGIN: "themelio"
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: bio pkg build go
#
#
##      - name: Build, Run BATS Tests
##        env:
##          HAB_ORIGIN: "themelio"
##          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##        run: ./biome/themelio-node/scripts/ci-test.sh


jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
