name: TestAndBuildGo17

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify-go17:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- go17 || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  verify-go:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.changed.outputs.build }}

    steps:
      - uses: actions/checkout@v2

      - name: Fetch
        run: git fetch

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "CHANGED=$(git diff --quiet HEAD origin/master -- go || echo true)" >> $GITHUB_ENV

      - name: Check For Changes
        id: changed
        if: ${{ env.CHANGED == 'true' }}
        run: echo "::set-output name=build::true"

  build-go17:
    needs: verify-go17
    if: contains(needs.verify-go17.outputs.build, 'true')
    runs-on: ubuntu-latest

    outputs:
      complete: ${{ steps.build.outputs.complete }}

    steps:
      - name: Thingy
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Set Enviromnent Variable
        shell: bash
        run: echo "COMPLETE=true" >> $GITHUB_ENV

      - name: Echo COMPLETE Environment Variable
        run: echo ${{ env.COMPLETE }}

      - name: Check For Changes
        id: build
        if: ${{ env.COMPLETE == 'true' }}
        run: echo "::set-output name=complete::true"

#      - uses: actions/checkout@v2
#
#      - uses: themeliolabs/actions-biome@v1
#        with:
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#
#      - name: Cache Biome
#        uses: actions/cache@v2
#        env:
#          CACHE_NAME: cache-biome
#        with:
#          path: ~/.hab/cache
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go17/plan.sh') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-

  build-go:
    needs:
      - verify-go17
      - verify-go
    if: contains(needs.verify-go.outputs.build, 'true') && contains(needs.verify-go17.outputs.build, '')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}


  build-go-if-go17-changed:
    needs:
      - verify-go17
      - verify-go
      - build-go17
    if: contains(needs.verify-go.outputs.build, 'true') && contains(needs.verify-go17.outputs.build, 'true') && contains(needs.build-go17.outputs.complete, 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Show Go17 Verify Output
        run: echo ${{ needs.verify-go17.outputs.build }}

      - name: Show Go17 Build Output
        run: echo ${{ needs.build-go17.outputs.complete }}



# I need to duplicate the go build step:
# build-go-go17-changed and build-go





#  build:
#    if: ${{ env.CHANGED == 'true' }}
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: themeliolabs/actions-biome@v1
#        with:
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          BIOME_SIGNING_KEY: ${{ secrets.BIOME_SIGNING_KEY }}
#
#      - name: Cache Biome
#        uses: actions/cache@v2
#        env:
#          CACHE_NAME: cache-biome
#        with:
#          path: ~/.hab/cache
#          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('go17/plan.sh') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}-
#
#      - name: Test
#        env:
#          HAB_ORIGIN: "themelio"
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: bio pkg build go17
#
#
##      - name: Build, Run BATS Tests
##        env:
##          HAB_ORIGIN: "themelio"
##          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##        run: ./biome/themelio-node/scripts/ci-test.sh