name: TestAndBuildGo17

on:
  pull_request:
    paths:
      - 'go17/**'
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/workflows/test

#      - uses: themeliolabs/actions-biome@v1

      - name: Test
        run: echo "Thingy"


#      - name: Build, Run BATS Tests
#        env:
#          HAB_ORIGIN: "themelio"
#          BIOME_PUBLIC_KEY: ${{ secrets.BIOME_PUBLIC_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: ./biome/themelio-node/scripts/ci-test.sh